apiVersion: v1
kind: Service
metadata:
  name: opsassistant
  namespace: goshop
  labels:
    app: opsassistant
spec:
  type: ClusterIP
  selector:
    app: opsassistant
  ports:
    - name: grpc
      port: 9191
      targetPort: 9191
