apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  namespace: goshop
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /live
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 8081

          - path: /ready
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 8081

          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 8081