scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: users
    scrape_interval: 5s
    static_configs:
      - targets: ['users:2112']
        labels: { service: users }

  - job_name: gateway
    scrape_interval: 5s
    static_configs:
      - targets: ['gateway:2112']
        labels: { service: gateway }
